// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt5OlVyblJQtntoR98M7WI2PUUPks0aso',
    appId: '1:788975090917:web:361ecacbbcba606491e80c',
    messagingSenderId: '788975090917',
    projectId: 'notification-bc7fc',
    authDomain: 'notification-bc7fc.firebaseapp.com',
    storageBucket: 'notification-bc7fc.firebasestorage.app',
    measurementId: 'G-NEQ302H9VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRN8DVfYCxqbzBluOitHXrgW1j7oejMY',
    appId: '1:788975090917:android:462edc4f1df88d0a91e80c',
    messagingSenderId: '788975090917',
    projectId: 'notification-bc7fc',
    storageBucket: 'notification-bc7fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxbEXMah1MVGTYGdad5D2_MLB9Xip5-I',
    appId: '1:788975090917:ios:dbc58d95e61b0f9991e80c',
    messagingSenderId: '788975090917',
    projectId: 'notification-bc7fc',
    storageBucket: 'notification-bc7fc.firebasestorage.app',
    iosBundleId: 'com.example.matchMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHxbEXMah1MVGTYGdad5D2_MLB9Xip5-I',
    appId: '1:788975090917:ios:dbc58d95e61b0f9991e80c',
    messagingSenderId: '788975090917',
    projectId: 'notification-bc7fc',
    storageBucket: 'notification-bc7fc.firebasestorage.app',
    iosBundleId: 'com.example.matchMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt5OlVyblJQtntoR98M7WI2PUUPks0aso',
    appId: '1:788975090917:web:03db4a0f3833198391e80c',
    messagingSenderId: '788975090917',
    projectId: 'notification-bc7fc',
    authDomain: 'notification-bc7fc.firebaseapp.com',
    storageBucket: 'notification-bc7fc.firebasestorage.app',
    measurementId: 'G-9BCCCJSNST',
  );
}
